### ISSUE TITLE
The telemetry operator should not deploy the comptue compoent unless asked.

### ISSUE THREAD

**Issue by SeanMooney** [openstack-k8s-operators/telemetry-operator#117]
as of https://github.com/openstack-k8s-operators/telemetry-operator/commit/6ee1b2f73696d314834bd5b9413d9e20745f56cd the telemetry operator is now deploying the infra-compute
components even when there are no compute nodes.

https://github.com/openstack-k8s-operators/telemetry-operator/blob/b2d4fc55966ad66e3fdab94f8345e8698cd69979/controllers/telemetry_controller.go#L375-L386

While the exact mechanism to control this, in general, is still under active discussion today the agreed acrchitreure is that if a service operator need to run Ansible against a dataplane node it would only do so if the dataplane operator create  a CR that the service operator reconciles.

while we are discussion selvel options the one that is likely to replace that is tagging OpenstackDataplaneNodes or OpenstackDataplaneRoles with an annotation that would cause the service operator to take the approate action

i.e. openstack.telemetry.infraCompute=true would be applied to the dataplane nodes that should have the infra compute ansible applied.

**Comment by SeanMooney** [comment]
the same issue extis for ceilometier comptue

https://github.com/openstack-k8s-operators/telemetry-operator/blob/b2d4fc55966ad66e3fdab94f8345e8698cd69979/controllers/telemetry_controller.go#L375-L386

however it does not create an AnsibleEE by default



the relevant section form the OpenStack control plane is before the defaulting webhooks ran was

telemetry:
    template:
      ceilometerCentral:
        passwordSelector:
          service: CeilometerPassword
        secret: osp-secret
        serviceUser: ceilometer

and this became after.


  telemetry:
    enabled: true
    template:
      ceilometerCentral:
        centralImage: quay.io/podified-antelope-centos9/openstack-ceilometer-central:current-podified
        customServiceConfig: '# add your customization here'
        description: A ceilometer agent
        initImage: quay.io/podified-antelope-centos9/openstack-ceilometer-central:current-podified
        notificationImage: quay.io/podified-antelope-centos9/openstack-ceilometer-notification:current-podified
        passwordSelector:
          service: CeilometerPassword
        secret: osp-secret
        serviceAccount: ""
        serviceUser: ceilometer
        sgCoreImage: quay.io/infrawatch/sg-core:latest
      ceilometerCompute:
        computeImage: quay.io/podified-antelope-centos9/openstack-ceilometer-compute:current-podified
        customServiceConfig: '# add your customization here'
        dataplaneInventoryConfigMap: dataplanerole-edpm-compute
        dataplaneSSHSecret: dataplane-ansible-ssh-private-key-secret
        description: A ceilometer compute agent
        initImage: quay.io/podified-antelope-centos9/openstack-ceilometer-compute:current-podified
        passwordSelector:
          service: ""
        playbook: deploy-ceilometer.yaml
        secret: ""
        serviceAccount: ""
        serviceUser: ""
      description: A ceilometer agent
      infraCompute:
        dataplaneInventoryConfigMap: dataplanerole-edpm-compute
        dataplaneSSHSecret: dataplane-ansible-ssh-private-key-secret
        description: An infra compute agent
        extravarsConfigMap: telemetry-infracompute-extravars
        nodeExporterImage: ""
        playbook: deploy-infra.yaml
        serviceAccount: ""
      rabbitMqClusterName: rabbitmq



in this case both the ceilometerCompute and infraCompute sections were incorrectly added and that triggered the creation fo the infra-compute AEE job because 

the CRD definition incorrectly default the dataplaneInventoryConfigMap

https://github.com/openstack-k8s-operators/telemetry-operator/blob/b2d4fc55966ad66e3fdab94f8345e8698cd69979/api/v1beta1/infracompute_types.go#L44-L46

https://github.com/openstack-k8s-operators/telemetry-operator/blob/b2d4fc55966ad66e3fdab94f8345e8698cd69979/api/v1beta1/ceilometercompute_types.go#L70-L72

those shoudl be required field and shoudl not have defaults.


the DataplaneSSHSecret field should also not have any default.

https://github.com/openstack-k8s-operators/telemetry-operator/blob/b2d4fc55966ad66e3fdab94f8345e8698cd69979/api/v1beta1/ceilometercompute_types.go#L70-L72

https://github.com/openstack-k8s-operators/telemetry-operator/blob/main/api/v1beta1/infracompute_types.go#L40-L42

i will open second issue for the embdeing of both CRDs in the telemetry CRD as that is problematic but with the current design both field shoudl be optional with no defaulting.

https://github.com/openstack-k8s-operators/telemetry-operator/blob/b2d4fc55966ad66e3fdab94f8345e8698cd69979/api/v1beta1/telemetry_types.go#L66C1-L72

**Comment by jlarriba** [comment]
Thanks Sean, we are aware of this issue. This is already being addressed by the PR: https://github.com/openstack-k8s-operators/telemetry-operator/pull/106 that separates all the objects from telemetry and https://github.com/openstack-k8s-operators/openstack-operator/pull/339 that makes openstack-operatoe deploy only ceilometercentral

**Comment by SeanMooney** [comment]
lookign at #106 it adresses some but not all of the defaulting issues. combined with https://github.com/openstack-k8s-operators/openstack-operator/pull/339

it would have the effect of not deploying the the compute bits when there are no comptues so that is good.

ill quickly push up a pr with some of the other changes i was thinking of for reference but #106 is proablty the better long term approch.
